from def_form.exceptions.def_formatter import DefStringTooLongException, InvalidMultilineParamsIndentException
from def_form.exceptions.def_formatter import TooManyInlineArgumentsException
from tests.constants import EXAMPLE_PATH

EXPECTED_ISSUES: list[DefStringTooLongException | TooManyInlineArgumentsException | InvalidMultilineParamsIndentException] = [
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:19", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:25", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:32", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:35", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:39", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:43", message="Too many inline args (3 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:46", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:51", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:55", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:59", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:64", message="Too many inline args (3 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:67", message="Too many inline args (3 > 2)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:70", message="Function definition too long (104 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:70", message="Too many inline args (3 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:73", message="Too many inline args (3 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:79", message="Too many inline args (3 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:82", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:86", message="Too many inline args (3 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:89", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:92", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:96", message="Function definition too long (142 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:96", message="Too many inline args (3 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:99", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:102", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:105", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:111", message="Too many inline args (5 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:119", message="Too many inline args (3 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:123", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:128", message="Too many inline args (3 > 2)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:149", message="Function definition too long (163 > 100)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:152", message="Function definition too long (126 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:160", message="Too many inline args (3 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:163", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:167", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:170", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:173", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:177", message="Function definition too long (108 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:177", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:183", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:186", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:190", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:194", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:198", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:203", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:218", message="Too many inline args (4 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:225", message="Too many inline args (6 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:228", message="Too many inline args (6 > 2)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:231", message="Too many inline args (5 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:234", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:240", message="Function definition too long (102 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:240", message="Too many inline args (5 > 2)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:243", message="Function definition too long (174 > 100)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:246", message="Function definition too long (199 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:246", message="Too many inline args (4 > 2)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:249", message="Function definition too long (127 > 100)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:252", message="Function definition too long (138 > 100)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:255", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:260", message="Function definition too long (118 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:260", message="Too many inline args (4 > 2)", description=None),
    InvalidMultilineParamsIndentException(path=f"{EXAMPLE_PATH}:269", message="Invalid multiline function parameters indentation (expected 4 spaces)", description=None),
    DefStringTooLongException(path=f"{EXAMPLE_PATH}:276", message="Function definition too long (129 > 100)", description=None),
    TooManyInlineArgumentsException(path=f"{EXAMPLE_PATH}:276", message="Too many inline args (5 > 2)", description=None),
]